---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: fedora-22

suites:
  - name: default
    run_list:
      - "recipe[chef-workstation::default]"
